<div class="row">

	<div class="span12">
		<div class="page-header">
			<h1><?= $this->org["name"]; ?> <small>Add Department</small></h1>
		</div>

		<ul class="breadcrumb">
		<?php if ($this->role == "SUPER_ADMIN"): ?>
			<li><a href="/manage">Settings</a> <span class="divider">/</span></li>
		<?php endif; ?>
			<li><a href="/manage/organization/id/<?= $this->org["id"]; ?>"><?= $this->org["name"]; ?></a> <span class="divider">/</span></li>
			<li class="active">Add Department</li>
		</ul>
	</div>

	<form method="post" class="well span8">
	  <?php if ($this->error): ?>
		<div class="alert alert-error">
			<strong>Error: </strong> <?= $this->message; ?>
		</div>
		<?php endif; ?>

		<label>Department Name</label> <input type="text" name="name"
			autofocus placeholder="Department Name" class="span8" />

		<button type="submit" class="btn btn-primary">Add Department</button>
		<a href="/manage/organization/id/<?= $this->org["id"]; ?>" class="btn btn-link">Cancel</a>
	</form>
</div>
