<div class="row">

	<div class="span12">
		<div class="page-header">
			<h1>Add Organization</h1>
		</div>
	</div>

	<form method="post" class="well span8">
	  <?php if ($this->error): ?>
		<div class="alert alert-error">
			<strong>Error: </strong> <?= $this->message; ?>
		</div>
		<?php endif; ?>

		<label>Organization Name</label> <input type="text" name="name"
			autofocus placeholder="Organization Name" class="span8" />

		<button type="submit" class="btn btn-primary">Add Organization</button>
		<a href="/manage" class="btn btn-link">Cancel</a>
	</form>
</div>
