<div class="row">

	<div class="span12">
		<div class="page-header">
			<h1><?= $this->org["name"]; ?> <small><?= $this->dept["name"]; ?></small>
			</h1>
		</div>

		<ul class="breadcrumb">
      <?php if ($this->role == "SUPER_ADMIN"): ?>
			<li><a href="/manage">Settings</a> <span class="divider">/</span></li>
		<?php endif; ?>
			<li><a href="/manage/organization/id/<?= $this->org["id"]; ?>"><?= $this->org["name"]; ?></a>
				<span class="divider">/</span></li>
			<li class="active"><?= $this->dept["name"]; ?></li>
		</ul>
	</div>

	<div class="span8">
<?=$this->partial("widgets/team-list.phtml", array("teams" => $this->teams)); ?>
<?=$this->partial("widgets/employee-list.phtml", array("employees" => $this->employees)); ?>
	</div>

	<div class="span4">
		<ul class="nav nav-tabs nav-stacked">
			<li><a href="/manage/add-team/organization/<?= $this->org["id"]; ?>/department/<?= $this->dept["id"]?>"> <span
					class="icon-plus"></span> Add Team</a></li>
			<li><a
				href="/manage/add-employee/organization/<?= $this->org["id"]; ?>"><span
					class="icon-plus"></span> Add Employee</a></li>
		</ul>
	</div>
</div>
