<div class="row">

	<div class="span12">
		<div class="page-header">
			<h1>Settings</h1>
		</div>
	</div>

	<div class="span8">
	<h3>Organizations</h3>
<?php if (count($this->organizations) < 1): ?>
   <div class="alert alert-info">No organizations found</div>
<?php else: ?>
   <ul>
   <?php foreach ($this->organizations as $_org): ?>
   <li>
      <a href="/manage/organization/id/<?= $_org["id"]; ?>">
      <?= $_org["name"]; ?>
      </a>
	</li>
   <?php endforeach; ?>
   </ul>
<?php endif; ?>
	</div>

	<div class="span4">
		<ul class="nav nav-tabs nav-stacked">
			<li><a href="/manage/add-organization"><span class="icon-plus"></span>
					Add Organization</a></li>
		</ul>
	</div>
</div>
