<form method="post" class="well span8">
	  <?php if ($this->error): ?>
		<div class="alert alert-error">
		<strong>Error: </strong> <?= $this->message; ?>
		</div>
		<?php endif; ?>

		<div class="clearfix"></div>

	<div class="pull-left">
		<label>New Skill </label> <input type="text" name="skill" autofocus
			placeholder="Skill" class="span4" />
	</div>

	<div class="pull-right span4">
		<label>Parent</label> <select name="parent" class="span4">
      <?php foreach ($this->skillSets as $_ss): ?>
		    <option value="<?= $_ss["s_id"]; ?>"><?= $_ss["s_name"]; ?></option>
		 <?php endforeach; ?>
		</select>
	</div>
		<?php
// TODO: Implement form inputs for skill def, desc, content, and assignment
?>
		<div class="clearfix"></div>
	<button type="submit" class="btn btn-primary">Add Skill</button>
	<a href="/skills/index/team/<?= $this->team["id"]; ?>"
		class="btn btn-link">Cancel</a>
</form>