<style>
.skillsTable th.narrow span {
   display: block;
   line-height: 100%;
   margin: 1px 5px;
   padding: 0;
   text-align: center;
}

.skillsTable th.narrow {
   width: 5px;
   height: 100px;
   padding: 0;
   margin: 0;
   overflow: hidden;
}
</style>

<div class="row">

	<div class="span12">
		<div class="page-header">
			<h1><?= $this->org["name"]; ?> <small><b><?= $this->dept["name"]; ?></b> <?= $this->team["name"]; ?></small>
			</h1>
		</div>

		<ul class="breadcrumb">
			<li><a href="/manage">Settings</a> <span class="divider">/</span></li>
			<li><a href="/manage/organization/id/<?= $this->org["id"]; ?>"><?= $this->org["name"]; ?></a>
				<span class="divider">/</span></li>
			<li><a
				href="/manage/department/id/<?= $this->dept["id"]; ?>/organization/<?= $this->org["id"]; ?>"><?= $this->dept["name"]; ?></a>
				<span class="divider">/</span></li>
			<li><a href="/manage/team/id/<?= $this->team["id"]; ?>"><?= $this->team["name"]; ?></a>
				<span class="divider">/</span></li>
			<li class="active">Skill Matrix</li>
		</ul>
	</div>

	<div class="span8">
		<h3>Skill Matrix</h3>
<?php if (count($this->skillSets) < 1): ?>
<div class="alert alert-info">No skill sets found</div>
<?php else: ?>
<?php $__users = array("Rodrigo", "Luci Fusco", "Samira"); ?>
<table class="table table-bordered skillsTable">
   <thead>
      <tr>
         <th></th>
         <?php foreach ($__users as $user): ?>
         <th class="narrow"><?php
          $str = "";
          for ($i = 0; $i < strlen($user); $i++) {
            $char = $user[$i] == " " ? "&nbsp;" : $user[$i];
            $str .= "<span>{$char}</span>";
          }
          echo $str;
          ?></th>
         <?php endforeach; ?>
      </tr>
   </thead>
   <tbody>
   <?php foreach ($this->skillSets["skillSets"] as $_ss): ?>
   <tr class="info">
      <td colspan="<?= count($__users) + 1; ?>"><h4><?= $_ss["name"]; ?></h4></td>
   </tr>
      <?php if (!empty($_ss["skills"])): ?>
         <?php foreach ($_ss["skills"] as $_skill): ?>
         <tr>
            <td width="100%"><?= $_skill["name"]; ?></td>
            <?php for($i = 0; $i < 3; $i++): ?>
            <td></td>
            <?php endfor; ?>
         </tr>
         <?php endforeach; ?>
      <?php endif; ?>
   <?php endforeach; ?>
   </tbody>
</table>
<?php endif; ?>
	</div>

	<div class="span4">
		<ul class="nav nav-tabs nav-stacked">
			<li><a
				href="/skills/add-skill-set/team/<?= $this->team["id"]; ?>">
					<span class="icon-plus"></span> Add Skill Set
			</a></li>
			<li><a
				href="/skills/add-skill/team/<?= $this->team["id"]; ?>">
					<span class="icon-plus"></span> Add Skill
			</a></li>
		</ul>
	</div>
</div>
